<div id="about_group">
  <p>Kupo, "express passion to vision," operates the traditional stage lighting gears from more than twenty years ago to today specialized innovated illumination manufacturer for venues throughtout Asia, Europe, America, Africa and Oceania.</p>
  <p>Established in 1979, as a leading manufacturer of entertainment lighting and associated equipment in Taiwan. The company is based in Taipei, Taiwan, an island country of south pacific nation with rich resources and excellent geographical position for exports and imports.</p>
  <p>Kupo supports a full range of vastly entertainment lighting fixtures (and custom-made products) with highest quality standards, high reliability, fasten delivery and professional services around the worldwide in the lighting market.</p>
  <p>A decade following Kupo's initial success, the principle of Kupo brings the compay to another technical leap, optic specialist, Kupo-Dichroic in 1992. The objective of Kupo-Dichroic is high quality and high volume products with precise control to meet the needs of customer from the high-tech automated systems, special training engineers and rigorous QC test.</p>
  <p>In year 2000, Kupo-Grip, another brand new domain is built. At the moment, a factory was set in Dong-Guang, China to manufacture the whole range of lighting stands with high quality and competitve pricing. Kupo-Grip not only offers lighting stands but also special effects to uesers to create lighting moments to remember.</p>
  <p>Kupo Shang-Hai, a subsidiary company, is found in 2002. This development supports Kupo easily and friendly handling the market inland China.</p>
  <p>In year 2004, a branch of Grip is on track, which is Kupo-Display. This specialist is totally leading the fashioned design ahead. The applications of Display are widely spread around the world, in leading spatial design, salon, shopping centers (shops), show room and galleries. Now, Kupo-Display catches the whole Asia market and is with recent entry into the America and Europe market.</p>
  <p>Kupo is multiplication in this entertainment market with unrivaled reputation. It has million dollars stock ready for rush requirement for customers all the time for user needs. The first minute you thought about Kupo, the belt is on and the request is just right in front. Express user needs with Kupo's passion, creates user a fantastic visual effects is the element of Kupo.</p>
</div>
